project:
  type: website
  output-dir: docs

website:
  title: "Klára Friesová"
  description: "This is a personal website of Klára Friesová, vegetation ecologist at the Department of Botany and Zoology, Faculty of Science, Masaryk University, Brno, Czech Republic."

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."

  #favicon: images/126677743.jpg
  #image: images/126677743.jpg

  navbar:
    title: "Klára Friesová"
    left:
      - text: "About me"
        href: index.qmd
      - text: "CV"
        href: about_me/CV.qmd
      - text: "Publications"
        href: about_me/publications.qmd
      - text: "Projects"
        href: projects/projects.qmd
      - text: "Skills and experience"
        href: about_me/skills_experience.qmd
      - text: "Teaching"
        href: teaching/teaching.qmd

format:
  html:
    theme: cosmo
    toc: true
    link-external-newwindow: true

filters:
  - lightbox
lightbox: auto
